# SPDX-FileCopyrightText: 2026 EZ2DIGITIZE contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Build the EZ2DIGITIZE Windows app (x64), a portable zip, with the backends inside.

    uv run --group packaging python tools/packaging/build_windows.py ^
        --backends build/backends/ez2d-backends-windows-x86_64.tar.gz ^
        --brush build/brush --smoke build/synthetic/images

Steps: one PyInstaller onedir with two programs over the same files:
`EZ2DIGITIZE.exe`, the GUI, without a console window, and `ez2d.exe`, the
CLI, a console program (a windowed program can't print to the terminal it
was started from). The backend archive goes to `_internal/backends`
(where the app looks for bundled tools), Brush next to it, and the folder
is zipped. Nothing is installed: unzip and run. Not code-signed yet
(Phase 6), so SmartScreen warns on first start.

`--smoke DIR` runs the same checks as the AppImage build, through
`ez2d.exe`, and checks that `EZ2DIGITIZE.exe` passes its self-test too.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

from build_appimage import EXCLUDED_MODULES, HERE, REPO, VIEWER_WEB, output, run, smoke

from ez2digitize import __version__

APP_NAME = "EZ2DIGITIZE"
CLI_NAME = "ez2d"
ICON_SIZES = (16, 24, 32, 48, 64, 128, 256)

SPEC = """\
# Generated by tools/packaging/build_windows.py; don't edit.
a = Analysis(
    [{entry!r}],
    pathex=[{src!r}],
    datas=[{licence!r}, {third_party!r}, {viewer!r}],
    excludes={excludes!r},
)
pyz = PYZ(a.pure)
gui = EXE(
    pyz, a.scripts, [], exclude_binaries=True, name={app!r}, console=False, icon={icon!r},
)
cli = EXE(
    pyz, a.scripts, [], exclude_binaries=True, name={cli!r}, console=True, icon={icon!r},
)
COLLECT(gui, cli, a.binaries, a.datas, name={app!r})
"""


def make_icon(out: Path) -> Path | None:
    """The app's SVG icon as a Windows .ico, drawn by Qt; None if that fails."""
    try:
        from PIL import Image
        from PySide6.QtCore import Qt
        from PySide6.QtGui import QGuiApplication, QImage, QPainter
        from PySide6.QtSvg import QSvgRenderer
    except ImportError:
        return None
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    _app = QGuiApplication.instance() or QGuiApplication([])
    renderer = QSvgRenderer(str(HERE / "ez2digitize.svg"))
    if not renderer.isValid():
        return None
    size = max(ICON_SIZES)
    image = QImage(size, size, QImage.Format.Format_RGBA8888)
    image.fill(Qt.GlobalColor.transparent)
    painter = QPainter(image)
    renderer.render(painter)
    painter.end()
    png = out / "icon.png"
    image.save(str(png))
    icon = out / f"{APP_NAME}.ico"
    with Image.open(png) as picture:
        picture.save(icon, sizes=[(s, s) for s in ICON_SIZES])
    return icon


def pyinstaller(out: Path) -> Path:
    icon = make_icon(out)
    spec = out / f"{APP_NAME}.spec"
    spec.write_text(
        SPEC.format(
            entry=str(HERE / "entry.py"),
            src=str(REPO / "src"),
            # Shown under Help -> Licenses.
            licence=(str(REPO / "LICENSE"), "."),
            third_party=(str(REPO / "THIRD_PARTY_LICENSES"), "."),
            viewer=(str(VIEWER_WEB), "ez2digitize/ui/viewer_web"),
            excludes=list(EXCLUDED_MODULES),
            app=APP_NAME,
            cli=CLI_NAME,
            icon=str(icon) if icon else None,
        )
    )
    run([
        sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean",
        "--distpath", out / "dist", "--workpath", out / "work", spec,
    ])  # fmt: skip
    return out / "dist" / APP_NAME


def add_backends(folder: Path, archive: Path) -> dict[str, object]:
    target = folder / "_internal" / "backends"
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    with tarfile.open(archive) as tar:
        tar.extractall(target, filter="data")
    info = json.loads((target / "BUILDINFO.json").read_text())
    return {k: info.get(k) for k in ("colmap", "openmvs", "openmvs_patches", "dynamic_libraries")}


def add_brush(folder: Path, release: Path) -> str:
    """Brush's release binary (statically linked: it needs only Windows' own DLLs)."""
    target = folder / "_internal" / "backends"
    shutil.copy2(release / "brush_app.exe", target / "bin" / "brush_app.exe")
    licenses = target / "licenses" / "brush"
    licenses.mkdir(parents=True, exist_ok=True)
    shutil.copy2(release / "LICENSE", licenses / "LICENSE")
    return output([target / "bin" / "brush_app.exe", "--version"]).strip()


def gui_self_test(folder: Path) -> None:
    """EZ2DIGITIZE.exe has no console, so only its exit code tells."""
    env = dict(os.environ, QT_QPA_PLATFORM="offscreen")
    done = subprocess.run(  # noqa: S603 - fixed argv
        [str(folder / f"{APP_NAME}.exe"), "--self-test"], env=env, timeout=300, check=False
    )
    if done.returncode != 0:
        raise SystemExit(f"{APP_NAME}.exe --self-test failed (exit code {done.returncode})")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--backends", type=Path, required=True, help="ez2d-backends-*.tar.gz")
    parser.add_argument("--brush", type=Path, metavar="DIR", help="unpacked Brush release")
    parser.add_argument("--out", type=Path, default=REPO / "build" / "windows")
    parser.add_argument("--smoke", type=Path, metavar="PHOTOS", help="test with these photos")
    args = parser.parse_args()
    if sys.platform != "win32":
        raise SystemExit("the Windows app is built on Windows")
    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=True)

    folder = pyinstaller(out)
    report: dict[str, object] = {"backends": add_backends(folder, args.backends.resolve())}
    if args.brush:
        report["brush"] = add_brush(folder, args.brush.resolve())
    archive = out / f"{APP_NAME}-{__version__}-windows-x86_64.zip"
    archive.unlink(missing_ok=True)
    shutil.make_archive(str(archive.with_suffix("")), "zip", folder.parent, folder.name)
    report["zip"] = archive.name
    report["size_mb"] = round(archive.stat().st_size / 2**20, 1)
    if args.smoke:
        report["smoke"] = smoke(
            folder / f"{CLI_NAME}.exe", args.smoke.resolve(), brush=args.brush is not None
        )
        gui_self_test(folder)
    (out / "report.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
