# SPDX-FileCopyrightText: 2026 EZ2DIGITIZE contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Turn run.json records into a Markdown report per machine."""

from __future__ import annotations

import json
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import Any

from ez2d_bench.record import RunRecord


def fmt_duration(seconds: float | None) -> str:
    if seconds is None:
        return "–"
    s = round(seconds)
    if s < 60:
        return f"{s}s"
    if s < 3600:
        return f"{s // 60}m {s % 60:02d}s"
    return f"{s // 3600}h {(s % 3600) // 60:02d}m"


def fmt_mb(mb: float | None) -> str:
    if mb is None:
        return "–"
    return f"{mb / 1024:.1f} GB" if mb >= 1024 else f"{mb:.0f} MB"


def fmt_num(value: Any) -> str:
    if value is None:
        return "–"
    if isinstance(value, float):
        return f"{value:.2f}"
    if isinstance(value, int) and value >= 10_000:
        return f"{value:,}"
    return str(value)


def _table(headers: list[str], rows: Iterable[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(cell.replace("|", "\\|") for cell in row) + " |" for row in rows]
    return lines


def _section(
    title: str,
    records: list[RunRecord],
    headers: list[str],
    row: Callable[[RunRecord], list[str]],
) -> list[str]:
    ok = [r for r in records if r.ok]
    if not ok:
        return []
    return [f"## {title}", "", *_table(headers, (row(r) for r in ok)), ""]


def _colmap_row(r: RunRecord) -> list[str]:
    c, m = r.config, r.metrics
    registered = f"{m.get('registered_images', 0)}/{m.get('total_images', '?')}"
    mapping = r.wall_s("mapper") or r.wall_s("global_mapper")
    return [
        r.dataset, r.label, str(c["max_image_size"]), c["matcher"], c["mapper"],
        "yes" if c["masks"] else "no", registered, fmt_num(m.get("models")),
        fmt_num(m.get("points")), fmt_num(m.get("mean_reprojection_error_px")),
        fmt_duration(r.wall_s("feature_extractor")),
        fmt_duration(r.wall_s(f"{c['matcher']}_matcher")), fmt_duration(mapping),
        fmt_duration(r.total_wall_s()), fmt_mb(r.peak("peak_rss_mb")),
        fmt_mb(r.peak("peak_swap_mb")),
    ]  # fmt: skip


def _openmvs_row(r: RunRecord) -> list[str]:
    c, m = r.config, r.metrics
    return [
        r.dataset, r.label, c["source"], str(c["resolution_level"]),
        "yes" if c["masks"] else "no", fmt_num(m.get("dense_points")),
        fmt_num(m.get("textured_faces", m.get("refined_faces", m.get("mesh_faces")))),
        fmt_duration(r.wall_s("DensifyPointCloud")), fmt_duration(r.wall_s("ReconstructMesh")),
        fmt_duration(r.wall_s("RefineMesh")), fmt_duration(r.wall_s("TextureMesh")),
        fmt_duration(r.total_wall_s()), fmt_mb(r.peak("peak_rss_mb")),
        fmt_mb(r.peak("peak_swap_mb")),
    ]  # fmt: skip


def _brush_row(r: RunRecord) -> list[str]:
    c, m = r.config, r.metrics
    return [
        r.dataset, r.label, c["source"], " ".join(c["args"]) or "(defaults)",
        fmt_num(m.get("splats")), fmt_num(m.get("eval_psnr")), fmt_duration(r.total_wall_s()),
        fmt_mb(r.peak("peak_vram_mb")), fmt_mb(r.peak("peak_gtt_mb")),
        fmt_mb(r.peak("peak_rss_mb")), fmt_mb(r.peak("peak_swap_mb")),
    ]  # fmt: skip


def merged_tool_versions(
    sysinfo: dict[str, Any] | None, records: list[RunRecord]
) -> dict[str, str | None]:
    """Versions seen across all runs; different runs may have used different tools."""
    seen: dict[str, list[str]] = {}
    sources = [r.tool_versions for r in records] + [(sysinfo or {}).get("tools", {})]
    for versions in sources:
        for name, version in versions.items():
            seen.setdefault(name, [])
            if version and version not in seen[name]:
                seen[name].append(version)
    return {name: " / ".join(v) or None for name, v in seen.items()}


def render(machine: str, sysinfo: dict[str, Any] | None, records: list[RunRecord]) -> str:
    lines = [f"# Feasibility results: {machine}", ""]
    lines += [
        "Generated by `tools/feasibility/bench.py report`. Do not edit by hand; "
        "write observations in `docs/feasibility/FINDINGS.md`.",
        "",
    ]
    tools = merged_tool_versions(sysinfo, records)
    if sysinfo:
        gpus = ", ".join(
            g.get("deviceName", g.get("name", "?"))
            + (f" ({g['driverInfo']})" if g.get("driverInfo") else "")
            for g in sysinfo.get("gpus", [])
        )
        lines += _table(
            ["", ""],
            [
                ["OS", f"{sysinfo.get('os')} ({sysinfo.get('kernel')}, {sysinfo.get('arch')})"],
                ["CPU", f"{sysinfo.get('cpu')}, {sysinfo.get('cpu_threads')} threads"],
                ["RAM", f"{sysinfo.get('ram_gb')} GB"],
                ["GPU", gpus or "–"],
                *[[k, v or "not found"] for k, v in tools.items()],
            ],
        )
        lines.append("")
    lines += [
        "Times are wall-clock. Peak RAM is the largest single step's process tree. "
        "VRAM, GTT and swap are increases over the level before the step started "
        "(system-wide, so other apps can skew them).",
        "",
    ]

    by_kind = {k: [r for r in records if r.kind == k] for k in ("colmap", "openmvs", "brush")}
    lines += _section(
        "COLMAP (CPU)", by_kind["colmap"],
        ["Dataset", "Run", "Max size", "Matcher", "Mapper", "Masks", "Registered", "Models",
         "Points", "Reproj px", "Extract", "Match", "Map", "Total", "Peak RAM", "Swap"],
        _colmap_row,
    )  # fmt: skip
    lines += _section(
        "OpenMVS (CPU)", by_kind["openmvs"],
        ["Dataset", "Run", "From", "Level", "Masks", "Dense pts", "Faces", "Densify", "Mesh",
         "Refine", "Texture", "Total", "Peak RAM", "Swap"],
        _openmvs_row,
    )  # fmt: skip
    lines += _section(
        "Brush (GPU)", by_kind["brush"],
        ["Dataset", "Run", "From", "Args", "Splats", "PSNR", "Time", "Peak VRAM", "Peak GTT",
         "Peak RAM", "Swap"],
        _brush_row,
    )  # fmt: skip

    problems = [r for r in records if not r.ok]
    if problems:
        lines += ["## Failed or skipped runs", ""]
        for r in problems:
            lines.append(f"- **{r.dataset} / {r.kind} / {r.label}** ({r.status}): {r.reason}")
            tail = r.steps[-1].tail[-15:] if r.steps and not r.steps[-1].ok else []
            if tail:
                lines += ["  <details><summary>last log lines</summary>", "", "  ```"]
                lines += [f"  {t}" for t in tail]
                lines += ["  ```", "  </details>"]
        lines.append("")

    notes = [(r, n) for r in records for n in r.notes]
    if notes:
        lines += ["## Notes from runs", ""]
        lines += [f"- {r.dataset} / {r.kind} / {r.label}: {n}" for r, n in notes]
        lines.append("")
    return "\n".join(lines)


def write_reports(results: Path, out_dir: Path) -> list[Path]:
    """One <machine>.md (and .json with all records) per machine folder."""
    written: list[Path] = []
    out_dir.mkdir(parents=True, exist_ok=True)
    for machine_dir in sorted(p for p in results.iterdir() if p.is_dir()):
        records = [
            RunRecord.from_dict(json.loads(p.read_text()))
            for p in sorted(machine_dir.rglob("run.json"))
        ]
        if not records:
            continue
        info_path = machine_dir / "sysinfo.json"
        info = json.loads(info_path.read_text()) if info_path.is_file() else None
        md = out_dir / f"{machine_dir.name}.md"
        md.write_text(render(machine_dir.name, info, records))
        payload = {"sysinfo": info, "runs": [_slim(r) for r in records]}
        (out_dir / f"{machine_dir.name}.json").write_text(json.dumps(payload, indent=2) + "\n")
        written.append(md)
    return written


def _slim(r: RunRecord) -> dict[str, Any]:
    """Record without local paths and log tails, suitable for committing."""
    return {
        "kind": r.kind, "label": r.label, "dataset": r.dataset, "status": r.status,
        "reason": r.reason, "config": r.config,
        "metrics": {k: v for k, v in r.metrics.items() if k != "result"},
        "steps": [
            {"name": s.name, "exit_code": s.exit_code, "wall_s": s.wall_s, "cpu_s": s.cpu_s,
             "peak_rss_mb": s.peak_rss_mb, "peak_vram_mb": s.peak_vram_mb,
             "peak_gtt_mb": s.peak_gtt_mb, "peak_swap_mb": s.peak_swap_mb}
            for s in r.steps
        ],
        "notes": r.notes, "tool_versions": r.tool_versions,
    }  # fmt: skip
